### ISSUE TITLE
Healthcare Authority user: Should be able to update help line numbers or other information useful for public

### ISSUE THREAD

**Issue by docsridhar** [TheSciFiMed/Covid-FLutter#20]
The healthcare authority (authorized user) should be able to update information which will be available to quarantined users:

1. Helpline numbers
2. Updates about disease
3. Local guidelines to be followed.
4. Useful sources of information

**Comment by shashwatxx** [comment]
All contacts already added in APP and Web Dashboard

**Comment by bgera** [comment]
another option is to refer a url that has contact numbers and maintained regularly by MOHWF and/or state authority eg. https://www.mohfw.gov.in/pdf/coronvavirushelplinenumber.pdf

**Comment by docsridhar** [comment]
Using an authentic URL is a good idea. Keep the app simple for now.
